/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Dominio.Cuenta;
import Persistencia.Conexion.ConexionBD;
import Persistencia.Conexion.IConexionBD;
import Persistencia.DAOS.ClienteDAO;
import Persistencia.DAOS.IClienteDAO;
import Persistencia.Excepciones.PersistenciaException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Interfaz Grafica de las cuentas
 * @author crist
 */
public class CuentasForm extends javax.swing.JFrame {

      IConexionBD conexionBD;
int idCliente;
    private static final Logger LOG = Logger.getLogger(ClienteDAO.class.getName());
    String cadenaConexion = "jdbc:mysql://localhost:3306/ProyectoBanco";
    String usuario = "root";
    String contra = "78357Cas";
    IClienteDAO clienteDAO;
    /**
     * Creates new form CuentasForm
     * @param idCliente
     */
    public CuentasForm(int idCliente) {
        this.idCliente=idCliente;
          conexionBD = new ConexionBD(cadenaConexion, usuario, contra);
    clienteDAO = new ClienteDAO(conexionBD); // Inicializa clienteDAO aquí
        initComponents();
    }

    /**
     * metodo que actualiza la tabla de las cuentas
     */
    public void ConsultaCuentas(){
  DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
    modelo.setRowCount(0);

    try {
        List<Cuenta> cuentas = clienteDAO.mostrarCuentas(idCliente);

        if (!cuentas.isEmpty()) {
            for (Cuenta cuenta : cuentas) {
                Object[] fila = {cuenta.getNoCuenta(), cuenta.getSaldo(), cuenta.getEstado(), cuenta.getFechaApertura(), cuenta.getIdCliente()};
                modelo.addRow(fila);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron cuentas para este cliente", "Cuentas no encontradas", JOptionPane.WARNING_MESSAGE);
        }
    } catch (PersistenciaException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al consultar las cuentas: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresarBoton = new javax.swing.JButton();
        agregarCuentaBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        generarFolioBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelarCuentaBoton = new javax.swing.JButton();
        historialBotno = new javax.swing.JButton();
        depositoBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresarBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        regresarBoton.setText("Regresar");
        regresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBotonActionPerformed(evt);
            }
        });

        agregarCuentaBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarCuentaBoton.setText("Agregar Cuenta");
        agregarCuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCuentaBotonActionPerformed(evt);
            }
        });

        jScrollPane2.setPreferredSize(new java.awt.Dimension(375, 80));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No. de cuenta", "Saldo", "Estado", "Fecha de apertura", "ID del cliente"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Transferencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        generarFolioBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        generarFolioBoton.setText("Generar Folio");
        generarFolioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarFolioBotonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cuentas");

        cancelarCuentaBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelarCuentaBoton.setText("Cancelar Cuenta");
        cancelarCuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCuentaBotonActionPerformed(evt);
            }
        });

        historialBotno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        historialBotno.setText("Historial");
        historialBotno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialBotnoActionPerformed(evt);
            }
        });

        depositoBoton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        depositoBoton.setText("Depositar");
        depositoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(historialBotno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(generarFolioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(depositoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelarCuentaBoton)
                        .addGap(32, 32, 32)
                        .addComponent(agregarCuentaBoton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCuentaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelarCuentaBoton)
                    .addComponent(depositoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarFolioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historialBotno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarCuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCuentaBotonActionPerformed
        // TODO add your handling code here:
        CrearCuentaForm creaCuenta = new CrearCuentaForm(idCliente);
        creaCuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_agregarCuentaBotonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TransferenciaForm transferencia = new TransferenciaForm();
        transferencia.setVisible(true);
        this.setVisible(false);     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBotonActionPerformed
InicioSesion iniciarSesion = new InicioSesion();
iniciarSesion.setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_regresarBotonActionPerformed

    private void generarFolioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarFolioBotonActionPerformed
        // TODO add your handling code here:
        GenerarFolioForm gff = new GenerarFolioForm();
        gff.setVisible(true);
        
    }//GEN-LAST:event_generarFolioBotonActionPerformed

    private void cancelarCuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCuentaBotonActionPerformed
        // TODO add your handling code here:
        String inputIdCuenta = JOptionPane.showInputDialog(this, "Ingrese el Numero de la cuenta que desea cancelar:", "Cancelar Cuenta", JOptionPane.QUESTION_MESSAGE);
    
    if (inputIdCuenta != null && !inputIdCuenta.isEmpty()) {
        try {
            int idCuenta = Integer.parseInt(inputIdCuenta);
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea cancelar la cuenta con ID " + idCuenta + "?", "Confirmación", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                clienteDAO.cancelarCuenta(idCuenta);
                ConsultaCuentas();
                JOptionPane.showMessageDialog(this, "La cuenta con ID " + idCuenta + " ha sido cancelada exitosamente.", "Cuenta Cancelada", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de cuenta ingresado no es válido. Por favor, ingrese un número entero.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (PersistenciaException ex) {
          Logger.getLogger(CuentasForm.class.getName()).log(Level.SEVERE, null, ex);
      }
    } else {
        JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la cuenta que desea cancelar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_cancelarCuentaBotonActionPerformed

    private void historialBotnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialBotnoActionPerformed
        // TODO add your handling code here:
        ConsultasForm consultas = new ConsultasForm(idCliente);
    consultas.setVisible(true);
    }//GEN-LAST:event_historialBotnoActionPerformed

    private void depositoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoBotonActionPerformed
        // TODO add your handling code here:
         DepositoForm deposito = new DepositoForm();
    deposito.setVisible(true);
    }//GEN-LAST:event_depositoBotonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton agregarCuentaBoton;
    private javax.swing.JButton cancelarCuentaBoton;
    private javax.swing.JButton depositoBoton;
    private javax.swing.JButton generarFolioBoton;
    private javax.swing.JButton historialBotno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton regresarBoton;
    // End of variables declaration//GEN-END:variables
}
